# fly.toml app configuration file generated for travel-app-premansh on 2025-07-16T18:36:49+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-app-premansh'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
